plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

android {
    namespace = "com.tealium.remotecommands.branch"
    compileSdk 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        buildConfigField 'String', 'TAG', "\"Tealium-Branch-$tealium_branch_version\""
        buildConfigField 'String', 'TEALIUM_BRANCH_VERSION', "\"$tealium_branch_version\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = true
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId 'com.tealium.remotecommands'
            artifactId 'branch'
            version "$tealium_branch_version"
            afterEvaluate {
                from components.release
            }
        }
    }
    // repositories {
    //     maven {
    //         url "s3://maven.tealiumiq.com/android/releases/"
    //         credentials(AwsCredentials) {
    //              accessKey AWS_ACCESS_KEY
    //              secretKey AWS_SECRET_KEY
    //              sessionToken AWS_SESSION_TOKEN
    //         }
    //     }
    // }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    // Branch
    api "io.branch.sdk.android:library:$branch_version"

    // Tealium
    api 'com.tealium:remotecommands:1.0.3'

    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.robolectric:robolectric:4.14.1"
    testImplementation "io.mockk:mockk:$mockk_version"
}

